/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kasm_Capstone */

#ifndef _Included_kasm_Capstone
#define _Included_kasm_Capstone
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kasm_Capstone
 * Method:    disassembleX64
 * Signature: ([B)[[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_kasm_Capstone_disassembleX64
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
