/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kasm_ExecutableBuffer */

#ifndef _Included_kasm_ExecutableBuffer
#define _Included_kasm_ExecutableBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kasm_ExecutableBuffer
 * Method:    allocate
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_kasm_ExecutableBuffer_allocate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     kasm_ExecutableBuffer
 * Method:    toArray
 * Signature: (Ljava/nio/ByteBuffer;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_kasm_ExecutableBuffer_toArray
  (JNIEnv *, jclass, jobject);

/*
 * Class:     kasm_ExecutableBuffer
 * Method:    protect
 * Signature: (Ljava/nio/ByteBuffer;Z)V
 */
JNIEXPORT void JNICALL Java_kasm_ExecutableBuffer_protect
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     kasm_ExecutableBuffer
 * Method:    execute0
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_kasm_ExecutableBuffer_execute0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     kasm_ExecutableBuffer
 * Method:    execute1
 * Signature: (Ljava/nio/ByteBuffer;J)J
 */
JNIEXPORT jlong JNICALL Java_kasm_ExecutableBuffer_execute1
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     kasm_ExecutableBuffer
 * Method:    execute2
 * Signature: (Ljava/nio/ByteBuffer;JJ)J
 */
JNIEXPORT jlong JNICALL Java_kasm_ExecutableBuffer_execute2
  (JNIEnv *, jclass, jobject, jlong, jlong);

/*
 * Class:     kasm_ExecutableBuffer
 * Method:    execute6
 * Signature: (Ljava/nio/ByteBuffer;JJJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_kasm_ExecutableBuffer_execute6
  (JNIEnv *, jclass, jobject, jlong, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     kasm_ExecutableBuffer
 * Method:    executeUnsafe
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_kasm_ExecutableBuffer_executeUnsafe
  (JNIEnv *, jclass, jobject);

/*
 * Class:     kasm_ExecutableBuffer
 * Method:    release
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_kasm_ExecutableBuffer_release
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     kasm_ExecutableBuffer
 * Method:    getAddress
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_kasm_ExecutableBuffer_getAddress
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
